var slideIndex = 1;
var ClassString = "SlideClass";
var Tags = document.getElementsByClassName("Tag");
for (var j = 0; j < Tags.length; j++) {
    // Get the variable generated by php and show the first slide of the slide group
    showSlides(1, ClassString.concat(Tags[j].getAttribute("Value")));
}

// Next/previous controls
function plusSlides(n, ClassSlide) {
    showSlides(slideIndex += n, ClassSlide);
}

// Thumbnail image controls
function currentSlide(n, ClassSlide) {
    showSlides(slideIndex = n, ClassSlide);
}

function showSlides(n, ClassSlide) {
    var i;
    var slides = document.getElementsByClassName(ClassSlide);
    if (n > slides.length) { slideIndex = 1 }
    if (n < 1) { slideIndex = slides.length }
    for (i = 0; i < slides.length; i++) {
        slides[i].style.display = "none";
    }
    slides[slideIndex - 1].style.display = "block";
}
